version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8383:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
#    environment:
#      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins_network
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins_network:
    driver: bridge
